name: Gerar e Publicar KML Concursos

on:
  schedule:
    - cron: '0 10 * * *'  # 07h da manhã no Brasil
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script Python
        run: python script.py

      - name: Criar pasta e copiar KML
        run: |
          mkdir -p public_kml
          cp ConcursosAtivos*.kml public_kml/

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_kml