name: Gerar KML Concursos Diariamente

on:
  schedule:
    - cron: '0 10 * * *'  # 07h da manhã no Brasil
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script Python
        run: python script.py

      - name: Upload do KML como artefato
        uses: actions/upload-artifact@v4
        with:
          name: kml-concursos
          path: ConcursosAtivos*.kml