name: Publicar KML no GitHub Pages

on:
  push:
    branches:
      - main  # Ou 'master', conforme sua branch principal
  workflow_run:
    workflows: ["Gerar KML Concursos Diariamente"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Copiar artefato do workflow anterior
        uses: actions/download-artifact@v4
        with:
          name: kml-concursos
          path: public_kml

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_kml